QR_Content: https://www.dungeon-lab.com/app-download.php#DGLAB-SOCKET#wss://ws.dungeon-lab.cn/a37d9dc9-6031-4b46-ae18-10b560087e4a
Channel_A_limit: 50
Channel_B_limit: 50
Wave_convert_ratio: 5
Debug: True
